name: Build

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
        with:
          fetch-depth: 0
      - name: Version
        id: version
        uses: paulhatch/semantic-version@v5.3.0
        with:
          tag_prefix: ""
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0.x'
      - name: Cache NuGet Packages
        uses: actions/cache@v3
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nuget-
      - name: Build Packages
        run: 
          dotnet pack -c Release -p:Version=${VERSION}  -p:PackageVersion=${PACKAGE_VERSION} .          
        env:
          DOTNET_CLI_TELEMETRY_OPTOUT: 1
          VERSION: ${{ steps.version.outputs.version }}.${{ steps.version.outputs.increment }}
          PACKAGE_VERSION: ${{ steps.version.outputs.version }}-preview.${{ steps.version.outputs.increment }}
      - name: Store Image Artifact
        uses: actions/upload-artifact@v3.1.3
        with:
          name: packages
          path: ./**/*.nupkg
  publish-preview:
    name: Publish Prerelease Packages
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download Packages Artifact
        uses: actions/download-artifact@v3.0.2
        with:
          name: packages
          path: ./packages
      - name: Publish Preview
        run: find . -name '*.nupkg' -exec dotnet nuget push "{}" --source "github" --api-key ${{ secrets.GITHUB_TOKEN }} \;
        shell: bash