name: Release Build

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
        with:
          fetch-depth: 0
      - name: Version
        id: version
        uses: paulhatch/semantic-version@v5.3.0
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
      - name: Build
        run: dotnet build -c Release
      - name: Create Packages
        run: dotnet pack -c Release -p:Version=${VERSION}  -p:PackageVersion=${PACKAGE_VERSION} --no-build --output .
        env:
          VERSION: ${{ steps.version.outputs.version }}.${{ steps.version.outputs.increment }}
          PACKAGE_VERSION: ${{ steps.version.outputs.version }}
      - name: Push to NuGet
        run: dotnet nuget push "*.nupkg" --api-key ${{secrets.nuget_api_key}} --source https://api.nuget.org/v3/index.json